package cs245quarterproject.src;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.text.MaskFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author mannyjuarez
 */
public class Sudoku extends javax.swing.JPanel {
    //Variable Declarations
    private int score = 540;
    public int totalScore = 0;
    boolean submitButton = false;
    List<JFormattedTextField> fieldList = new ArrayList<>();
    public int[] answers = new int[]{3,5,1,9,2,
                                     2,9,6,8,5,7,3,1,
                                     4,7,2,9,3,8,
                                     6,1,4,2,
                                     1,2,3,6,8,5,4,9,
                                     7,5,9,6,
                                     6,7,8,1,3,4,
                                     9,8,3,4,5,2,7,6,
                                     7,4,6,8,1};
    
    /**
     * Creates new form Sudoku
     */
    public Sudoku(String oldScore) {
        initComponents();
        
        //Hide alert box in background
        jOptionPane.setVisible(false);
        
        //Convert oldScore to int
        totalScore = Integer.parseInt(oldScore);
        
        //Load Date and Time
        showDate();
        showTime();
    }
    
    //Show "date"
    void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MMMM dd, yyyy");
        date.setText(s.format(d));
    }
    
    //Show "time"
    void showTime(){
        new Timer(0, new ActionListener(){
            
            @Override
            public void actionPerformed(ActionEvent e){
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                time.setText(s.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        Quit = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jFormattedTextField11 = new javax.swing.JFormattedTextField();
        jFormattedTextField12 = new javax.swing.JFormattedTextField();
        jFormattedTextField13 = new javax.swing.JFormattedTextField();
        jFormattedTextField14 = new javax.swing.JFormattedTextField();
        jFormattedTextField15 = new javax.swing.JFormattedTextField();
        jFormattedTextField16 = new javax.swing.JFormattedTextField();
        jFormattedTextField17 = new javax.swing.JFormattedTextField();
        jFormattedTextField18 = new javax.swing.JFormattedTextField();
        jFormattedTextField19 = new javax.swing.JFormattedTextField();
        jFormattedTextField20 = new javax.swing.JFormattedTextField();
        jFormattedTextField21 = new javax.swing.JFormattedTextField();
        jFormattedTextField22 = new javax.swing.JFormattedTextField();
        jFormattedTextField23 = new javax.swing.JFormattedTextField();
        jFormattedTextField24 = new javax.swing.JFormattedTextField();
        jFormattedTextField25 = new javax.swing.JFormattedTextField();
        jFormattedTextField26 = new javax.swing.JFormattedTextField();
        jFormattedTextField27 = new javax.swing.JFormattedTextField();
        jFormattedTextField28 = new javax.swing.JFormattedTextField();
        jFormattedTextField29 = new javax.swing.JFormattedTextField();
        jFormattedTextField30 = new javax.swing.JFormattedTextField();
        jFormattedTextField31 = new javax.swing.JFormattedTextField();
        jFormattedTextField32 = new javax.swing.JFormattedTextField();
        jFormattedTextField33 = new javax.swing.JFormattedTextField();
        jFormattedTextField34 = new javax.swing.JFormattedTextField();
        jFormattedTextField35 = new javax.swing.JFormattedTextField();
        jFormattedTextField36 = new javax.swing.JFormattedTextField();
        jFormattedTextField37 = new javax.swing.JFormattedTextField();
        jFormattedTextField38 = new javax.swing.JFormattedTextField();
        jFormattedTextField39 = new javax.swing.JFormattedTextField();
        jFormattedTextField40 = new javax.swing.JFormattedTextField();
        jFormattedTextField41 = new javax.swing.JFormattedTextField();
        jFormattedTextField42 = new javax.swing.JFormattedTextField();
        jFormattedTextField43 = new javax.swing.JFormattedTextField();
        jFormattedTextField44 = new javax.swing.JFormattedTextField();
        jFormattedTextField45 = new javax.swing.JFormattedTextField();
        jFormattedTextField46 = new javax.swing.JFormattedTextField();
        jFormattedTextField47 = new javax.swing.JFormattedTextField();
        jFormattedTextField48 = new javax.swing.JFormattedTextField();
        jFormattedTextField49 = new javax.swing.JFormattedTextField();
        jFormattedTextField50 = new javax.swing.JFormattedTextField();
        jFormattedTextField51 = new javax.swing.JFormattedTextField();
        jFormattedTextField52 = new javax.swing.JFormattedTextField();
        jFormattedTextField53 = new javax.swing.JFormattedTextField();
        jFormattedTextField54 = new javax.swing.JFormattedTextField();
        jOptionPane = new javax.swing.JOptionPane();

        setMaximumSize(new java.awt.Dimension(600, 400));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sudoku.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setBackground(new java.awt.Color(234, 234, 234));
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/grid300x300.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 62, -1, -1));

        date.setText("date");
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 15, -1, 20));

        time.setText("time");
        add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 15, -1, 20));

        Quit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Quit.setText("Quit");
        Quit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        add(Quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 90, -1));

        Submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Submit.setText("Submit");
        Submit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, -1));

        try{
            jFormattedTextField1 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField1);
        jFormattedTextField1.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField1.setBorder(null);
        jFormattedTextField1.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 65, 30, 30));

        try{
            jFormattedTextField2 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField2);
        jFormattedTextField2.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField2.setBorder(null);
        jFormattedTextField2.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 65, 30, 30));

        try{
            jFormattedTextField3 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField3);
        jFormattedTextField3.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField3.setBorder(null);
        jFormattedTextField3.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 65, 30, 30));

        try{
            jFormattedTextField4 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField4);
        jFormattedTextField4.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField4.setBorder(null);
        jFormattedTextField4.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 65, 30, 30));

        try{
            jFormattedTextField5 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField5);
        jFormattedTextField5.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField5.setBorder(null);
        jFormattedTextField5.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 65, 30, 30));

        try{
            jFormattedTextField6 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField6);
        jFormattedTextField6.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField6.setBorder(null);
        jFormattedTextField6.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 97, 30, 30));

        try{
            jFormattedTextField7 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField7);
        jFormattedTextField7.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField7.setBorder(null);
        jFormattedTextField7.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 97, 30, 30));

        try{
            jFormattedTextField8 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField8);
        jFormattedTextField8.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField8.setBorder(null);
        jFormattedTextField8.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 97, 30, 30));

        try{
            jFormattedTextField9 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField9);
        jFormattedTextField9.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField9.setBorder(null);
        jFormattedTextField9.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 97, 30, 30));

        try{
            jFormattedTextField10 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField10);
        jFormattedTextField10.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField10.setBorder(null);
        jFormattedTextField10.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 97, 30, 30));

        try{
            jFormattedTextField11 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField11);
        jFormattedTextField11.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField11.setBorder(null);
        jFormattedTextField11.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 97, 30, 30));

        try{
            jFormattedTextField12 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField12);
        jFormattedTextField12.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField12.setBorder(null);
        jFormattedTextField12.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 97, 30, 30));

        try{
            jFormattedTextField13 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField13);
        jFormattedTextField13.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField13.setBorder(null);
        jFormattedTextField13.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 97, 30, 30));

        try{
            jFormattedTextField14 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField14);
        jFormattedTextField14.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField14.setBorder(null);
        jFormattedTextField14.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 131, 30, 30));

        try{
            jFormattedTextField15 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField15);
        jFormattedTextField15.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField15.setBorder(null);
        jFormattedTextField15.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 131, 30, 30));

        try{
            jFormattedTextField16 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField16);
        jFormattedTextField16.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField16.setBorder(null);
        jFormattedTextField16.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 131, 30, 30));

        try{
            jFormattedTextField17 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField17);
        jFormattedTextField17.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField17.setBorder(null);
        jFormattedTextField17.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 131, 30, 30));

        try{
            jFormattedTextField18 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField18);
        jFormattedTextField18.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField18.setBorder(null);
        jFormattedTextField18.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 131, 30, 30));

        try{
            jFormattedTextField19 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField19);
        jFormattedTextField19.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField19.setBorder(null);
        jFormattedTextField19.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 131, 30, 30));

        try{
            jFormattedTextField20 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField20);
        jFormattedTextField20.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField20.setBorder(null);
        jFormattedTextField20.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 164, 30, 30));

        try{
            jFormattedTextField21 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField21);
        jFormattedTextField21.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField21.setBorder(null);
        jFormattedTextField21.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 164, 30, 30));

        try{
            jFormattedTextField22 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField22);
        jFormattedTextField22.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField22.setBorder(null);
        jFormattedTextField22.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 164, 30, 30));

        try{
            jFormattedTextField23 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField23);
        jFormattedTextField23.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField23.setBorder(null);
        jFormattedTextField23.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 164, 30, 30));

        try{
            jFormattedTextField24 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField24);
        jFormattedTextField24.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField24.setBorder(null);
        jFormattedTextField24.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField24.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 198, 30, 30));

        try{
            jFormattedTextField25 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField25);
        jFormattedTextField25.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField25.setBorder(null);
        jFormattedTextField25.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField25.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 198, 30, 30));

        try{
            jFormattedTextField26 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField26);
        jFormattedTextField26.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField26.setBorder(null);
        jFormattedTextField26.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 198, 30, 30));

        try{
            jFormattedTextField27 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField27);
        jFormattedTextField27.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField27.setBorder(null);
        jFormattedTextField27.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField27.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 198, 30, 30));

        try{
            jFormattedTextField28 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField28);
        jFormattedTextField28.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField28.setBorder(null);
        jFormattedTextField28.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField28.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 198, 30, 30));

        try{
            jFormattedTextField29 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField29);
        jFormattedTextField29.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField29.setBorder(null);
        jFormattedTextField29.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField29.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 198, 30, 30));

        try{
            jFormattedTextField30 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField30);
        jFormattedTextField30.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField30.setBorder(null);
        jFormattedTextField30.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField30.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 198, 30, 30));

        try{
            jFormattedTextField31 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField31);
        jFormattedTextField31.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField31.setBorder(null);
        jFormattedTextField31.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField31.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 198, 30, 30));

        try{
            jFormattedTextField32 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField32);
        jFormattedTextField32.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField32.setBorder(null);
        jFormattedTextField32.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField32.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 231, 30, 30));

        try{
            jFormattedTextField33 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField33);
        jFormattedTextField33.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField33.setBorder(null);
        jFormattedTextField33.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField33.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 231, 30, 30));

        try{
            jFormattedTextField34 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField34);
        jFormattedTextField34.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField34.setBorder(null);
        jFormattedTextField34.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField34.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 231, 30, 30));

        try{
            jFormattedTextField35 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField35);
        jFormattedTextField35.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField35.setBorder(null);
        jFormattedTextField35.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField35.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jFormattedTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField35ActionPerformed(evt);
            }
        });
        add(jFormattedTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 231, 30, 30));

        try{
            jFormattedTextField36 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField36);
        jFormattedTextField36.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField36.setBorder(null);
        jFormattedTextField36.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField36.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 262, 30, 30));

        try{
            jFormattedTextField37 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField37);
        jFormattedTextField37.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField37.setBorder(null);
        jFormattedTextField37.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField37.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 262, 30, 30));

        try{
            jFormattedTextField38 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField38);
        jFormattedTextField38.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField38.setBorder(null);
        jFormattedTextField38.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField38.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 262, 30, 30));

        try{
            jFormattedTextField39 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField39);
        jFormattedTextField39.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField39.setBorder(null);
        jFormattedTextField39.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField39.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 262, 30, 30));

        try{
            jFormattedTextField40 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField40);
        jFormattedTextField40.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField40.setBorder(null);
        jFormattedTextField40.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField40.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 262, 30, 30));

        try{
            jFormattedTextField41 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField41);
        jFormattedTextField41.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField41.setBorder(null);
        jFormattedTextField41.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField41.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 262, 30, 30));

        try{
            jFormattedTextField42 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField42);
        jFormattedTextField42.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField42.setBorder(null);
        jFormattedTextField42.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField42.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 295, 30, 30));

        try{
            jFormattedTextField43 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField43);
        jFormattedTextField43.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField43.setBorder(null);
        jFormattedTextField43.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField43.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 295, 30, 30));

        try{
            jFormattedTextField44 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField44);
        jFormattedTextField44.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField44.setBorder(null);
        jFormattedTextField44.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField44.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 295, 30, 30));

        try{
            jFormattedTextField45 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField45);
        jFormattedTextField45.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField45.setBorder(null);
        jFormattedTextField45.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField45.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 295, 30, 30));

        try{
            jFormattedTextField46 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField46);
        jFormattedTextField46.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField46.setBorder(null);
        jFormattedTextField46.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField46.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jFormattedTextField46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField46ActionPerformed(evt);
            }
        });
        add(jFormattedTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 295, 30, 30));

        try{
            jFormattedTextField47 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField47);
        jFormattedTextField47.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField47.setBorder(null);
        jFormattedTextField47.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField47.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 295, 30, 30));

        try{
            jFormattedTextField48 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField48);
        jFormattedTextField48.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField48.setBorder(null);
        jFormattedTextField48.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField48.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 295, 30, 30));

        try{
            jFormattedTextField49 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField49);
        jFormattedTextField49.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField49.setBorder(null);
        jFormattedTextField49.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField49.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 295, 30, 30));

        try{
            jFormattedTextField50 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField50);
        jFormattedTextField50.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField50.setBorder(null);
        jFormattedTextField50.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField50.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField50, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 329, 30, 30));

        try{
            jFormattedTextField51 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField51);
        jFormattedTextField51.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField51.setBorder(null);
        jFormattedTextField51.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField51.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField51, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 329, 30, 30));

        try{
            jFormattedTextField52 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField52);
        jFormattedTextField52.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField52.setBorder(null);
        jFormattedTextField52.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField52.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 329, 30, 30));

        try{
            jFormattedTextField53 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField53);
        jFormattedTextField53.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField53.setBorder(null);
        jFormattedTextField53.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField53.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 329, 30, 30));

        try{
            jFormattedTextField54 = new javax.swing.JFormattedTextField(new MaskFormatter("#"));
        } catch (ParseException e){}
        fieldList.add(jFormattedTextField54);
        jFormattedTextField54.setBackground(new java.awt.Color(238, 238, 238));
        jFormattedTextField54.setBorder(null);
        jFormattedTextField54.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextField54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField54.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add(jFormattedTextField54, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 329, 30, 30));
        add(jOptionPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField35ActionPerformed

    private void jFormattedTextField46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField46ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        //Variable Declarations
        //"wrong" for future attemps
        int wrong = 0;
        
        //First time set "score"
        //Future attempts set "wrong"
        if(submitButton == false)
        {
            score = checkScore(score);
            totalScore += score;
        }
        else 
        {
            //Properly set "wrong" here because otherwise it will bypass the if statements 
            wrong = 540;
            wrong = checkScore(wrong);
        }
        
        //After first attempt switch boolean
        submitButton = true;
        
        ////////////////////////////////////////////////////////////////////////
        System.out.println("score: " + score);
        System.out.println("wrong: " + wrong);
        ////////////////////////////////////////////////////////////////////////
        
        if(score == 540 || wrong == 540)
        {
            //Go to "GameOverGui
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            frame.getContentPane().removeAll();
            frame.repaint();

            GameOverGUI gg = new GameOverGUI(Integer.toString(totalScore));
            frame.add(gg);
            frame.setVisible(true);
        }
        else
        {
            //Centering alert based on frame position
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            jOptionPane.showMessageDialog(frame, "Answer is incorrect please try again.");
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        //Go to "GameOverGui
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();
        frame.repaint();

        GameOverGUI gg = new GameOverGUI(Integer.toString(totalScore));
        frame.add(gg);
        frame.setVisible(true);
    }//GEN-LAST:event_QuitActionPerformed
    
    public int checkScore(int x)
    {
        String reference;
        
        for (int i = 0; i < fieldList.size(); i++)
        {
            reference = fieldList.get(i).getText().trim();
            if(reference.isEmpty())
            {
                x -= 10;
            }
            else if(Integer.parseInt(reference) != answers[i])
            {
                x -= 10;
            }
        }
        return x;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Quit;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel date;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField17;
    private javax.swing.JFormattedTextField jFormattedTextField18;
    private javax.swing.JFormattedTextField jFormattedTextField19;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField20;
    private javax.swing.JFormattedTextField jFormattedTextField21;
    private javax.swing.JFormattedTextField jFormattedTextField22;
    private javax.swing.JFormattedTextField jFormattedTextField23;
    private javax.swing.JFormattedTextField jFormattedTextField24;
    private javax.swing.JFormattedTextField jFormattedTextField25;
    private javax.swing.JFormattedTextField jFormattedTextField26;
    private javax.swing.JFormattedTextField jFormattedTextField27;
    private javax.swing.JFormattedTextField jFormattedTextField28;
    private javax.swing.JFormattedTextField jFormattedTextField29;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField30;
    private javax.swing.JFormattedTextField jFormattedTextField31;
    private javax.swing.JFormattedTextField jFormattedTextField32;
    private javax.swing.JFormattedTextField jFormattedTextField33;
    private javax.swing.JFormattedTextField jFormattedTextField34;
    private javax.swing.JFormattedTextField jFormattedTextField35;
    private javax.swing.JFormattedTextField jFormattedTextField36;
    private javax.swing.JFormattedTextField jFormattedTextField37;
    private javax.swing.JFormattedTextField jFormattedTextField38;
    private javax.swing.JFormattedTextField jFormattedTextField39;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField40;
    private javax.swing.JFormattedTextField jFormattedTextField41;
    private javax.swing.JFormattedTextField jFormattedTextField42;
    private javax.swing.JFormattedTextField jFormattedTextField43;
    private javax.swing.JFormattedTextField jFormattedTextField44;
    private javax.swing.JFormattedTextField jFormattedTextField45;
    private javax.swing.JFormattedTextField jFormattedTextField46;
    private javax.swing.JFormattedTextField jFormattedTextField47;
    private javax.swing.JFormattedTextField jFormattedTextField48;
    private javax.swing.JFormattedTextField jFormattedTextField49;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField50;
    private javax.swing.JFormattedTextField jFormattedTextField51;
    private javax.swing.JFormattedTextField jFormattedTextField52;
    private javax.swing.JFormattedTextField jFormattedTextField53;
    private javax.swing.JFormattedTextField jFormattedTextField54;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

}
