/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CirclePackage;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.BorderFactory;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Stream17
 */
public class CirclePanel extends javax.swing.JPanel implements ChangeListener {
    private ArrayList<JButton> buttonList;
    private String[]Colors = {"Red","Yellow","Blue","Purple","Green"};
    /**
     * Creates new form CirclePanel
     */
    public CirclePanel() {
        initComponents();
        spawnButtons();
        //remove(CircleButton2);
        setVisible(true);
        setOpaque(true);
    }
    
    /**
     * Incomplete method
     * SpawnButtons needs to randomly pick 5 of our nine buttons and set their action commands to Colors
     * from the Colors array.
     * It also needs to set the Buttons' ImageIcons in the format 
     * new ImageIcon(Colors[i] + "Button.png")
     */
    private void spawnButtons(){
        CircleButton1.setActionCommand(Colors[0]);
        CircleButton1.setIcon(new ImageIcon(Colors[0] + "Button.png"));
        
        CircleButton4.setActionCommand(Colors[1]);
        CircleButton4.setIcon(new ImageIcon(Colors[1] + "Button.png"));
        
        CircleButton8.setActionCommand(Colors[2]);
        CircleButton8.setIcon(new ImageIcon(Colors[2] + "Button.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CircleButton1 = new javax.swing.JButton();
        CircleButton2 = new javax.swing.JButton();
        CircleButton3 = new javax.swing.JButton();
        CircleButton4 = new javax.swing.JButton();
        CircleButton5 = new javax.swing.JButton();
        CircleButton6 = new javax.swing.JButton();
        CircleButton7 = new javax.swing.JButton();
        CircleButton8 = new javax.swing.JButton();
        CircleButton9 = new javax.swing.JButton();

        CircleButton1.setContentAreaFilled(false);
        CircleButton1.setBorderPainted(false);
        CircleButton1.setBorder(BorderFactory.createEmptyBorder());
        //CircleButton1.setIcon(new ImageIcon("RedButton.png"));
        CircleButton1.addChangeListener(this);

        CircleButton2.setContentAreaFilled(false);
        CircleButton2.setBorderPainted(false);
        CircleButton2.setBorder(BorderFactory.createEmptyBorder());
        CircleButton2.addChangeListener(this);

        CircleButton3.setContentAreaFilled(false);
        CircleButton3.setBorderPainted(false);
        CircleButton3.setBorder(BorderFactory.createEmptyBorder());
        CircleButton3.addChangeListener(this);

        CircleButton4.setContentAreaFilled(false);
        CircleButton4.setBorderPainted(false);
        CircleButton4.setBorder(BorderFactory.createEmptyBorder());
        CircleButton4.addChangeListener(this);

        CircleButton5.setContentAreaFilled(false);
        CircleButton5.setBorderPainted(false);
        CircleButton5.setBorder(BorderFactory.createEmptyBorder());
        CircleButton5.addChangeListener(this);

        CircleButton6.setContentAreaFilled(false);
        CircleButton6.setBorderPainted(false);
        CircleButton6.setBorder(BorderFactory.createEmptyBorder());
        CircleButton6.addChangeListener(this);

        CircleButton7.setContentAreaFilled(false);
        CircleButton7.setBorderPainted(false);
        CircleButton7.setBorder(BorderFactory.createEmptyBorder());
        CircleButton7.addChangeListener(this);

        CircleButton8.setContentAreaFilled(false);
        CircleButton8.setBorderPainted(false);
        CircleButton8.setBorder(BorderFactory.createEmptyBorder());
        CircleButton8.addChangeListener(this);

        CircleButton9.setContentAreaFilled(false);
        CircleButton9.setBorderPainted(false);
        CircleButton9.setBorder(BorderFactory.createEmptyBorder());
        CircleButton9.addChangeListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(CircleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CircleButton7)
                .addGap(180, 180, 180)
                .addComponent(CircleButton9)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(CircleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(CircleButton3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(CircleButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CircleButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CircleButton6)
                                .addGap(59, 59, 59)
                                .addComponent(CircleButton8)))))
                .addGap(47, 47, 47))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CircleButton1, CircleButton2, CircleButton3, CircleButton4, CircleButton5, CircleButton6, CircleButton7, CircleButton8, CircleButton9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(CircleButton3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CircleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(CircleButton7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(CircleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CircleButton5)
                                .addGap(34, 34, 34)
                                .addComponent(CircleButton6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CircleButton8)
                                .addGap(34, 34, 34)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CircleButton2)
                            .addComponent(CircleButton9))))
                .addGap(28, 28, 28))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CircleButton1, CircleButton2, CircleButton3, CircleButton4, CircleButton5, CircleButton6, CircleButton7, CircleButton8, CircleButton9});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CircleButton1;
    private javax.swing.JButton CircleButton2;
    private javax.swing.JButton CircleButton3;
    private javax.swing.JButton CircleButton4;
    private javax.swing.JButton CircleButton5;
    private javax.swing.JButton CircleButton6;
    private javax.swing.JButton CircleButton7;
    private javax.swing.JButton CircleButton8;
    private javax.swing.JButton CircleButton9;
    // End of variables declaration//GEN-END:variables

    @Override
    /**
     * The method stateChanged is used to swap the pictures of a button when the mouse is rolled over it.
     * It gets the color by getting the source of the change event ce and getting the action command of
     * its source.
     * 
     * It then gets the source's ButtonModel and checks to see if the mouse is rolled over it.
     * The sources icon is then set to the appropriate picture.
     * @param ce the changeEvent passed into this method
     */
    public void stateChanged(ChangeEvent ce) {
        String color = ((JButton)ce.getSource()).getActionCommand();
        ButtonModel mod = ((JButton)ce.getSource()).getModel();
        if(mod.isRollover())
             ((JButton)ce.getSource()).setIcon(new ImageIcon(color + "ButtonRollover.png"));
        
        if(!mod.isRollover())
            ((JButton)ce.getSource()).setIcon(new ImageIcon(color + "Button.png"));
    }
}
